INSERT INTO food VALUES (null , 'Pincho Tortilla', 'Pincho de torilla de patata casera, recien hecha, con los mejores productos del mercado', 200, 2, 'Carta', 'PinchoTortilla.jpg');
INSERT INTO food VALUES (null , 'Croquetas Caseras', 'Una croqueta casera gigante, casi tan ricas como las de tu madre', 60, 0.7, 'Carta', 'CroquetasCaseras.jpg');
INSERT INTO food VALUES (null , 'Pincho Moruno', 'Brocheta elaborado con dados de carne de pollo o cerdo adonado en pimenton y ajo', 250, 2.5, 'Carta', 'PinchoMoruno.jpg');
INSERT INTO food VALUES (null , 'Chorizo Frito', 'Chorizo frito rico rico', 300, 1.5, 'Carta', 'ChorizoFrito.jpg');
INSERT INTO food VALUES (null , 'Tira Panceta', 'Tira de panceta a la plancha, fina y crujiente', 300, 1.5, 'Carta', 'TiraPanceta.jpg');
INSERT INTO food VALUES (null , 'Oreja Gallega', 'Tipica oreja gallega, repetiras', 200, 4, 'Carta', 'OrejaGallega.jpg');
INSERT INTO food VALUES (null , 'Patatas Salsas', 'Patatas fritas con 5 salsa diferentes para variar', 225, 4, 'Carta', 'PatatasSalsas.jpg');
INSERT INTO food VALUES (null , 'Patatas Cabrales', 'Patatas fritas con una riquisima salsa de queso cabrales', 200, 4, 'Carta', 'PatatasCabrales.jpg');
INSERT INTO food VALUES (null , 'Patatas Bastardas', 'Patatas bastardas, cuidado que pican', 175, 4, 'Carta', 'PatatasBastardas.jpg');
INSERT INTO food VALUES (null , 'Provolone Mermelada', 'Queso provolone al horno, con una fina capa de mermelada de tomate', 250, 4, 'Carta', 'ProvoloneMermelada.jpg');
INSERT INTO food VALUES (null , 'Termpura Verdura', 'Tempura de un selecto conjunto de verduras rebozadas', 100, 4, 'Carta', 'TermpuraVerdura.jpg');
INSERT INTO food VALUES (null , 'Flamenquito JyQ', 'Jamon york y queso enrollados entorno a un rico filete de pollo', 60, 4, 'Carta','FlamenquitoJyQ.jpg');
INSERT INTO food VALUES (null , 'Huevos Rotos Jamon', 'Huevos fritos con patatas cocidas en laminas acompanado del mejor jamon serrano', 300, 5, 'Carta', 'HuevosRotosJamon.jpg');
INSERT INTO food VALUES (null , 'Huevos Rotos Chorizo', 'Huevos fritos con patatas cocidas en laminas acompanado del mejor chorizo', 300, 5, 'Carta', 'HuevosRotosChorizo.jpg');
INSERT INTO food VALUES (null , 'Mejillones Salsa', 'Mejillones con una riquisima salsa que le da su toque destacado', 150, 5, 'Carta', 'MejillonesSalsa.jpg');
INSERT INTO food VALUES (null , 'Puntillitas', 'Chopitos fritos rebozados con harina', 150, 5, 'Carta', 'Puntillitas.jpg');
INSERT INTO food VALUES (null , 'Calamares', 'Tiernos calamares rebozados', 175, 5, 'Carta', 'Calamares.jpg');
INSERT INTO food VALUES (null , 'Cachopo Cerdo', 'Cachopo de cerdo relleno de jamon, queso, champinon y pimientos de piquillo', 450, 10, 'Carta', 'CachopoCerdo.jpg');
INSERT INTO food VALUES (null , 'Tortilla Patata', 'Ven con tu familia a disfrutar de la mejor totilla de patata casera, pidenosla a tu gusto y te la preparamos en un periquete', 1600, 15, 'Especialidades', 'TortillaPatata.jpg');
INSERT INTO food VALUES (null , 'Empanada Bonito', 'Empanada casera, hecha por encargo, rellena de bonito con pisto', 1500, 15, 'Especialidades', 'EmpanadaBonito.jpg');
INSERT INTO food VALUES (null , 'Empanada JyQ', 'Empanada casera, hecha por encargo, rellena de jamon york, queso, chorizo y tomate natural', 1500, 15, 'Especialidades', 'EmpanadaJyQ.jpg');
INSERT INTO food VALUES (null , 'Empanada Champinon', 'Empanada casera, hecha por encargo, rellena de champinon, espinaca fresca, queso y bechamel', 1600, 15, 'Especialidades', 'EmpanadaChampinon.jpg');
INSERT INTO food VALUES (null , 'Hamburguesa Buey', 'Hamburguesa de buey, completada con varios toppings a elegir (queso de cabra, pepinillo, lechuga...)', 500, 7, 'Hamburguesas', 'HamburguesaBuey.jpg');
INSERT INTO food VALUES (null , 'Hamburguesa Ternera', 'Hamburguesa de ternera, completada con varios toppings a elegir (queso de cabra, pepinillo, lechuga...)', 500, 6, 'Hamburguesas', 'HamburguesaTernera.jpg');
INSERT INTO food VALUES (null , 'Croqueta Champinon', 'Croqueta vegana rellena de champinon', 60, 0.7, 'Carta Vegana', 'CroquetaChampinon.jpg');
INSERT INTO food VALUES (null , 'Croqueta Espinaca', 'Croqueta vegana rellena de espinacas', 60, 0.7, 'Carta Vegana', 'CroquetaEspinaca.jpg');
INSERT INTO food VALUES (null , 'Pincho Seitan', 'Pincho moruno seiten, delicioso y sano plato vegano', 200, 2.5, 'Carta Vegana', 'PinchoSeitan.jpg');
INSERT INTO food VALUES (null , 'Hamburguesa Lentejas', 'Hamburguesa vegana, con base de lentejas', 325, 6, 'Hamburguesa Vegana', 'HamburguesaLentejas.jpg');
INSERT INTO food VALUES (null , 'Hamburguesa Soja', 'Hamburguesa vegana, con base de soja texturizada con champinon', 325, 6, 'Hamburguesa Vegana', 'HamburguesaSoja.jpg');
INSERT INTO food VALUES (null , 'Hamburguesa Tofu', 'Hamburguesa vegana, con base de tofu con espinacas', 325, 6, 'Hamburguesa Vegana', 'HamburguesaTofu.jpg');
INSERT INTO food VALUES (null , 'Campero Vegano', 'Seitan, esparrago, guacamole, lechuga, tomate y mayonesa vegana', 150, 6, 'Hamburguesa Vegana', 'CamperoVegano.jpg');